interface Game {
  rank: string
  score: string
}

interface Skill {
  rank: string
  level: string
  exp: string
}

export interface CharacterType {
  abyssalSire: Game
  agility: Skill
  alchemicalHydra: Game
  atk: Skill
  barrows: Game
  bountyHunterHunter: Game
  bountyHunterRogue: Game
  bryophyta: Game
  callisto: Game
  cerberus: Game
  chaosEle: Game
  chaosFanatic: Game
  cluescrollBeg: Game
  cluescrollEasy: Game
  cluescrollElite: Game
  cluescrollHard: Game
  cluescrollMast: Game
  cluescrollMed: Game
  cluescrolls: Game
  construction: Skill
  cook: Skill
  corporealBeast: Game
  corruptedGauntlet: Game
  cox: Game
  coxHard: Game
  craft: Skill
  crazyArchaeologist: Game
  dagPrime: Game
  dagRex: Game
  dagSupreme: Game
  def: Skill
  derangedArchaeologist: Game
  farm: Skill
  fish: Skill
  fletch: Skill
  fm: Skill
  gauntlet: Game
  giantMole: Game
  graardor: Game
  grotesqueGuardians: Game
  herb: Skill
  hespori: Game
  hp: Skill
  hunt: Skill
  jad: Game
  kbd: Game
  kq: Game
  kraken: Game
  kreeArra: Game
  krilTsutsaroth: Game
  leaguePoints: Game
  lms: Game
  magic: Skill
  mimic: Game
  mine: Skill
  nex: Game
  nightmare: Game
  obor: Game
  overall: Skill
  phantomMuspah: Game
  phosanisNightmare: Game
  prayer: Skill
  pvpArena: Game
  range: Skill
  rc: Skill
  riftsClosed: Game
  sarachnis: Game
  scorpia: Game
  skotizo: Game
  slayer: Skill
  smith: Skill
  soulwars: Game
  str: Skill
  tempoross: Game
  thermonuclearSmokeDevil: Game
  thief: Skill
  toa: Game
  toaHard: Game
  tob: Game
  tobHard: Game
  venenatis: Game
  vetion: Game
  vorkath: Game
  wc: Skill
  wintertodt: Game
  zalcano: Game
  zilyana: Game
  zuk: Game
  zulrah: Game
}
